### ISSUE TITLE
Price oracle contract

### ISSUE THREAD

**Issue by maurolacy** [osmosis-labs/mesh-security#99]
Instead of [simple-price-feed](https://github.com/osmosis-labs/mesh-security/tree/main/contracts/consumer/simple-price-feed), implement a proper price oracle contract that gets its info from a DEX such as Osmosis. This may require querying of price information over IBC.

Support multiple crypto currencies / crypto currencies pairs, both from a local (Consumer side) DEX, or from a remote (Consumer side / other) DEX, over IBC.

Use [TWAP](https://en.wikipedia.org/wiki/Time-weighted_average_price) or similar to get a stable price estimation for a crypto currency pair.

**Comment by JakeHartnell** [comment]
Going to have a couple of these. IMO an easy one to start with would be `band-price-feeder` , I would:
- Make a new folder dedicated to price-feeders: `contracts/consumer/price-feeders/`
- Move `simple-price-feeder` in there
- Base a new `band-price-feeder` contract off the example contract in cw-band but conforming to the standard interface as demonstrated in simple-price-feeder: https://github.com/bandprotocol/cw-band

**Comment by maurolacy** [comment]
We can start working on this soon. Let's discuss offline.

**Comment by maurolacy** [comment]
Some comments / guidance from Osmosis on how to implement a price Oracle using the Osmosis DEX:

_So for on chain queries, we want to query via Stargate Query

https://github.com/zodiac-protocol/tokenfactorytest/blob/c4044443ef83528be613e5b6fccd16f57542ea7d/contracts/tokenfactory_hooks/src/contract.rs#L189

Path here is the query path, and msg is the binary-ized protobuf query message

We basically rely on cosmwasm’s querier to dispatch the query to osmosis, and receive results._

**Comment by uint** [comment]
> So for on chain queries, we want to query via Stargate Query

[This looks less boilerplatey](https://github.com/osmosis-labs/osmosis-rust/blob/main/packages/osmosis-std/src/types/osmosis/twap/v1beta1.rs#L330), I'll give it a try.

**Comment by uint** [comment]
I've been poking at this and the scaffold I have so far is a "price feed provider" contract (deployed on Osmosis) and "price feed consumer". Provider has an admin that can add/remove subscriptions (IBC connections). Provider will require some sort of endblock capability to periodically send all subscribers updates - is that something we can do?

**Comment by uint** [comment]
Current design I have:

## `osmosis-price-provider`

To be deployed on Osmosis. The contract has an `admin` set at instantiation. The contract is capable of handling multiple IBC connections.

After a successful IBC handshake, the `admin` can bind the IBC connection to a denom through a local exec msg. Once a channel is bound, it's an active subscription. Every epoch every active subscription is sent (fire-and-forget) an IBC message with the current twap for their particular trading pair.

For triggering the periodic updates, I'm hoping we can figure this out via the [`epochs`](https://docs.osmosis.zone/osmosis-core/modules/epochs) native module on Osmosis, but if I understand Osmosis docs properly, we'd need some help from them.

## `remote-price-feed`

To be deployed on consumer chains. The contract doesn't have an admin. It can handle a single IBC connection to the `osmosis-price-provider` (or another provider with the same API?).

It works pretty much like `simple-price-feed`, but instead of manually updating the exchange rate, it receives updates over IBC.

Along with the exchange rate, the contract stores a timestamp of when the update was received. If for some reason the exchange rate is outdated (configurable threshold), querying for the price returns an error.

**Comment by maurolacy** [comment]
Just seen this, sorry for not commenting / reviewing earlier.

Some comments:

- Handling multiple IBC connections on the Price provider is fine. I see now that this is to support multiple consumer contracts querying the Osmosis DEX for pricing info through the contract.
I would still support a token pair there, not just a denom. Because a Consumer could want pricing info against another token besides Osmosis. Imagine a (future) Juno consumer chain that is secured by CosmosHub, and queries the Osmosis contract for the JUNO/ATOM price.
- I would put the query loop on the Price consumer contract. That simplifies the Osmosis contract, and allows for multiple, configurable querying frequencies per Consumer. This would require sudo / end blocker privileges on each Consumer, but that's something a Consumer is already doing for the virtual-staking contract. So, more of the same setup in a sense.
